// <auto-generated />
namespace MVCApp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Changeddatabasetableformats : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changeddatabasetableformats));
        
        string IMigrationMetadata.Id
        {
            get { return "201904262002315_Changed database table formats"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
